name: CD Pipeline

on:
  push:
    branches:
      - feature/AmazingFeature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-nginx:latest .
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-nginx:latest

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-nginx:latest \
            --docker-registry-server-url https://${{ secrets.AZURE_ACR_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.AZURE_ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Restart App Service
        run: az webapp restart --name ${{ secrets.AZURE_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
