name: Deploy to NGINX Server

on:
  push:
    branches:
      - feature/AmazingFeature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to server via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/myapp"

      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}  # Add your server IP in GitHub Secrets
          username: ${{ secrets.SSH_USER }}  # Add your SSH username in GitHub Secrets
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/your-app/"
          strip_components: 1
            